/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Analizador_Lexico;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aceve
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Texto_de_Entrada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area_de_Resultado = new javax.swing.JTextArea();
        Texto_Cuadro_Result = new javax.swing.JLabel();
        Boton_Analizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area_De_Texto = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Texto_de_Entrada.setText("Texto a Analizar:");

        Area_de_Resultado.setColumns(20);
        Area_de_Resultado.setRows(5);
        jScrollPane1.setViewportView(Area_de_Resultado);

        Texto_Cuadro_Result.setText("Resultado:");

        Boton_Analizar.setText("Analizar");
        Boton_Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AnalizarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(Area_De_Texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Boton_Analizar))
                    .addComponent(Texto_de_Entrada)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Texto_Cuadro_Result)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto_de_Entrada)
                    .addComponent(Texto_Cuadro_Result))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Analizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * 
     * @param evt, en esta parte se ejecuta la prueba del lexer 
     * 
     */
    
    private void Boton_AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AnalizarActionPerformed
        try
        {
            ProbarLexer();
        }
        catch (IOException ex)
        {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_Boton_AnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
 
    /**
     * 
     * @throws IOException, Metodo para probar el lexer
     */
    public void ProbarLexer() throws IOException
    {
        File fichero = new File  ("entrada.txt");
        PrintWriter writer;
        try 
        {
            writer = new PrintWriter (fichero);
            writer.print(Area_De_Texto.getText());
            writer.close();
        }
        catch (FileNotFoundException ex)
        {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*
        *En esta parte se almacena el contenido escrito en el cuadro de ingreso 
        *en un archivo *.txt para pasarlo al analizador
        */
        Reader reader = new BufferedReader(new FileReader("entrada.txt"));
        /*
        *Abro el archivo fichero.txt
        */
        Lexer lexer = new Lexer (reader);
        String resultado ="";
        while (true)
        {
            Token token = lexer.yylex();
            if (token == null)
            {
                resultado = resultado + "EOF";
                /*
                *Se realiza este proceso porque flex solo acepat las entras de tipo
                *java.io.Reader
                */
                Area_de_Resultado.setText(resultado);
                return;
            }
            switch (token)
            {
                case TKN_ERROR:
                    resultado = resultado + "Error, el simbolo o sentencia no fue recnocido \n";
                    break;
                case TKN_ID: case TKN_INT:
                    resultado = resultado + "TOKEN: " + token + " " + lexer.lexeme + "\n";
                    break;
                default:
                    resultado = resultado + "TOKEN: " + token + "\n";  
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane Area_De_Texto;
    private javax.swing.JTextArea Area_de_Resultado;
    private javax.swing.JButton Boton_Analizar;
    private javax.swing.JLabel Texto_Cuadro_Result;
    private javax.swing.JLabel Texto_de_Entrada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
